spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/indidea
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 300MB
      max-file-size: 200MB
server:
  port: 8888